modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Ninjdai1/CornExpansion/issues"
license = "GPLv3"

[[mods]]
modId = "cornexpansion"
version = "${version}"
displayName = "[Let's Do Addon] Corn Expansion"
authors = '''
Ninjdai
KalWantsPizza
Satisfy
'''
description = '''
A corn addon for Farm&Charm
'''
logoFile = "assets/cornexpansion/icon.png"

[[dependencies.cornexpansion]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cornexpansion]]
modId = "farm_and_charm"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"
